# 生产环境配置

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    url: jdbc:mysql://47.242.50.132:3306/vcc?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ostudio007
    driver-class-name: com.mysql.cj.jdbc.Driver


# 日志配置
logging:
  file:
    name: vcc.log
  level:
    root: WARN
    com.egao: ERROR
    com.baomidou.mybatisplus: ERROR
